# Generated by Django 3.2.9 on 2021-11-27 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Handler', '0002_delete_qrcodemodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='QrCodeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='qr_up_images/')),
            ],
        ),
    ]
